language: python

services:
  - postgresql

addons:
  postgresql: "9.6"

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

env:
  global:
    - secure: "pPCYxAdBBMpl0hRWPtX5q75eBKbxU9Vccrms72D3pB4yrL6cKOrR3+/3BYU+81J18dZHXxaetSJ5DmbarYrOi5tnuigr7E6Z4zEA7RBBNyUfIe+g2sNK8tDBQjRrPpgHlKAFpySPOdU2E4Z0fi58EkTf7UfwVHyx3ouUqiwfNqn8UwCsWwGjeIfmyHi1Sj7DzTHNYLr9HfceGF/EkW+UDy2ZqDmzyuyCCwtzeKr7qDPpUM2G8HNf25F4pdNiv8S1T13cHFfXD/cCvGFFW2fs6a7LN0yfOUi7jpp3eobDW1NWbEfA2A3PyQS+jtIdxgS0mwnOrVeBFxuI5dWD1+RLdaESOQunJKErWDl2N7FAEdZCegV3udseuGMomUjwSNonlI1X8NYG9Wcz3Ks0ZS3KdaQuDATwDWPMWUi2uZIdbhDuzBKNIK3kAY2ck1Tk4+W/hgDtiCusGiGT2ip77R07kaH8ohr1v5T4FL5Bhv7IHDganWg3SXBgeGrQY9XGJevkFePgfxgQLKI1/oxb38xhzXduxGHHb/vJrVCSUvVmgLZoZDCvMt3i6T6zt3aEwgEYG6xdlkH0JRF45k4XM3FzPMJEl8RQydvgUAfroB7OkD8jhCc20lBAhDJpAfGqJuDn+9OdyYzsrLoybwahmqL4UKnDeDq+t+veppnDrc6ghPw="

install:
  - pip install poetry tox tox-travis coveralls

before_script:
  - psql -c 'create database sirbot;' -U postgres

script:
  - tox

after_success:
  - coveralls

deploy:
  - provider: script
    script: poetry publish --username Ovv --password $PYPI_PASS --build
    on:
      repo: pyslackers/sir-bot-a-lot-2
      branch: master
      python: '3.7'
      tags: true
